# Generated by Django 5.0 on 2025-01-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
