# Generated by Django 5.0 on 2025-01-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedcontent',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='project.project'),
            preserve_default=False,
        ),
    ]
