# Generated by Django 5.0 on 2025-01-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_aigeneratedcontent_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
