# Generated by Django 5.0 on 2025-01-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_ai_response_project_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
    ]
