# Generated by Django 5.0 on 2025-02-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_uploadedfile_project_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_name',
        ),
    ]
