# Generated by Django 5.0 on 2025-02-04 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_city_county_state_alter_project_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aigeneratedcontent',
            options={'verbose_name_plural': 'AI Generated Content'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='templatesection',
            options={'verbose_name_plural': 'Template Sections'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'verbose_name_plural': 'Uploaded Files'},
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='service_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='project.city'),
        ),
    ]
