# Generated by Django 5.0 on 2025-02-06 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_aigeneratedcontent_options_alter_city_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aigeneratedcontent',
            name='project',
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('target_region', models.CharField(max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('prompt', models.TextField(blank=True, null=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zip_codes', to='project.city')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='project.template')),
            ],
        ),
        migrations.AddField(
            model_name='aigeneratedcontent',
            name='page',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='project.page'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
