# Generated by Django 5.0 on 2025-02-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_service_state_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='service',
            field=models.ManyToManyField(related_name='pages', to='project.service'),
        ),
    ]
