# Generated by Django 5.0 on 2025-02-06 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_page_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='project.project'),
            preserve_default=False,
        ),
    ]
