# Generated by Django 5.0 on 2025-02-06 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_uploadedfile_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='service',
        ),
        migrations.AddField(
            model_name='page',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='project.service'),
            preserve_default=False,
        ),
    ]
