# Generated by Django 5.0 on 2025-02-06 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_remove_page_service_page_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='service',
        ),
        migrations.AddField(
            model_name='state',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='project.project'),
            preserve_default=False,
        ),
    ]
