# Generated by Django 5.0 on 2025-02-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_alter_state_abbreviation_alter_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesection',
            name='default_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
