# Generated by Django 5.0 on 2025-02-07 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_templatesection_default_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='service',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
