# Generated by Django 5.0 on 2025-02-07 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_remove_page_service_delete_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='service_type',
        ),
        migrations.AddField(
            model_name='project',
            name='homepage_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_homepage_template', to='project.template'),
        ),
        migrations.AddField(
            model_name='project',
            name='service_page_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_service_page_template', to='project.template'),
        ),
        migrations.AddField(
            model_name='project',
            name='service_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
