# Generated by Django 5.0 on 2025-02-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_remove_page_service_type_project_homepage_template_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='target_region',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
