# Generated by Django 5.0 on 2025-02-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_remove_page_target_region_uploadedfile_temperature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='service_type',
        ),
    ]
