# Generated by Django 5.0 on 2025-02-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_remove_uploadedfile_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='homepage_ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
