# Generated by Django 5.0 on 2025-02-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_project_homepage_ai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
