# Generated by Django 5.0 on 2025-02-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_project_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='head',
            field=models.TextField(blank=True, null=True),
        ),
    ]
