# Generated by Django 5.0 on 2025-02-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_template_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesection',
            name='ai_response_sample',
            field=models.TextField(blank=True, null=True),
        ),
    ]
