# Generated by Django 5.0 on 2025-02-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_templatesection_ai_response_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='images',
            field=models.TextField(blank=True, null=True),
        ),
    ]
