# Generated by Django 5.0 on 2025-02-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_page_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
