# Generated by Django 5.0 on 2025-02-24 12:38

import django_grapesjs.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_page_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='html',
            field=django_grapesjs.models.fields.GrapesJsHtmlField(blank=True, null=True),
        ),
    ]
