# Generated by Django 5.0 on 2025-02-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_alter_page_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='model',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)')], default='anthropic', max_length=20),
        ),
        migrations.AlterField(
            model_name='page',
            name='html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
