# Generated by Django 5.0 on 2025-02-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_project_model_alter_page_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='homepage_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='homepage_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
