# Generated by Django 5.0 on 2025-02-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_project_homepage_css_project_homepage_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='homepage_footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='homepage_header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
