# Generated by Django 5.0 on 2025-02-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_project_homepage_footer_project_homepage_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='homepage_head',
            field=models.TextField(blank=True, null=True),
        ),
    ]
