# Generated by Django 5.0 on 2025-02-28 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_project_homepage_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='homepage_css',
        ),
        migrations.RemoveField(
            model_name='project',
            name='homepage_footer',
        ),
        migrations.RemoveField(
            model_name='project',
            name='homepage_head',
        ),
        migrations.RemoveField(
            model_name='project',
            name='homepage_header',
        ),
        migrations.RemoveField(
            model_name='project',
            name='homepage_html',
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ai_response', models.TextField(blank=True, null=True)),
                ('html', models.TextField(blank=True, null=True)),
                ('css', models.TextField(blank=True, null=True)),
                ('head', models.TextField(blank=True, null=True)),
                ('header', models.TextField(blank=True, null=True)),
                ('footer', models.TextField(blank=True, null=True)),
                ('complete_html', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='project.project')),
            ],
        ),
    ]
