# Generated by Django 5.0 on 2025-02-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_remove_project_homepage_css_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
