# Generated by Django 5.0 on 2025-03-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_alter_projectpage_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpage',
            options={'verbose_name_plural': 'Project Pages'},
        ),
        migrations.AddField(
            model_name='page',
            name='complete_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='footer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='head',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='page',
            name='header',
            field=models.TextField(blank=True, null=True),
        ),
    ]
