# Generated by Django 5.0 on 2025-03-04 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_alter_projectpage_options_page_complete_html_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='project.template'),
        ),
    ]
