# Generated by Django 5.0 on 2025-03-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_city_complete_html_city_css_city_footer_city_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
