# Generated by Django 5.0 on 2025-03-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_city_ai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='prompt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
