# Generated by Django 5.0 on 2025-03-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_city_prompt_project_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
