# Generated by Django 5.0 on 2025-04-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_alter_project_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tracking_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
