# Generated by Django 5.0 on 2025-04-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_project_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tracking_code_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tracking_code_head',
            field=models.TextField(blank=True, null=True),
        ),
    ]
