# Generated by Django 5.0 on 2025-04-03 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0042_project_tracking_code_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tracking_code',
        ),
    ]
