# Generated by Django 5.0 on 2025-04-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_projectpageversions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPageVersions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('city_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='project.city')),
            ],
            options={
                'verbose_name_plural': 'City Pages Versions',
            },
        ),
    ]
