# Generated by Django 5.0 on 2025-04-07 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_citypageversions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectPageVersions',
            new_name='ProjectPageVersion',
        ),
        migrations.CreateModel(
            name='ProjectPromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.CharField(max_length=10000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='project.project')),
            ],
            options={
                'verbose_name_plural': 'Project Prompts History',
            },
        ),
    ]
