# Generated by Django 5.0 on 2025-04-08 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0046_rename_projectpageversions_projectpageversion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPromptHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete_html', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt', models.CharField(max_length=10000)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='project.city')),
            ],
            options={
                'verbose_name_plural': 'Project Prompts History',
            },
        ),
    ]
