# Generated by Django 5.0 on 2025-04-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_cityprompthistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityprompthistory',
            options={'verbose_name_plural': 'City Prompts History'},
        ),
        migrations.AlterField(
            model_name='project',
            name='tracking_code_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='tracking_code_head',
            field=models.TextField(blank=True, default=''),
        ),
    ]
