# Generated by Django 5.0 on 2025-04-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_alter_cityprompthistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='base_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='base_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
