# Generated by Django 5.0 on 2025-04-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_project_base_html_projectpage_base_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='css',
        ),
        migrations.RemoveField(
            model_name='city',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='city',
            name='head',
        ),
        migrations.RemoveField(
            model_name='city',
            name='header',
        ),
        migrations.RemoveField(
            model_name='city',
            name='html',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='base_html',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='css',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='head',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='header',
        ),
        migrations.RemoveField(
            model_name='projectpage',
            name='html',
        ),
        migrations.AddField(
            model_name='city',
            name='content_html',
            field=models.TextField(blank=True, null=True),
        ),
    ]
