# Generated by Django 5.0 on 2025-04-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_remove_city_css_remove_city_footer_remove_city_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_domain',
            field=models.CharField(blank=True, help_text='Custom domain configured for the project', max_length=255, null=True),
        ),
    ]
