# Generated by Django 5.0 on 2025-04-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_project_client_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='netlify_site_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='netlify_site_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
