# Generated by Django 5.0 on 2025-04-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0052_project_netlify_site_id_project_netlify_site_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='emailjs_public_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='emailjs_service_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='emailjs_template_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
