# Generated by Django 5.0 on 2025-05-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_project_emailjs_public_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
