# Generated by Django 5.0 on 2025-05-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0054_projectpage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
