# Generated by Django 5.0 on 2025-05-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_projectpage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
