# Generated by Django 5.0 on 2025-05-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_project_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
