# Generated by Django 5.0 on 2025-05-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0057_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('completed', 'Completed')], default='queued', max_length=20),
        ),
    ]
