# Generated by Django 5.0 on 2025-05-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0058_city_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='scripts',
            field=models.TextField(blank=True, null=True),
        ),
    ]
