# Generated by Django 5.0 on 2025-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0060_projectpage_meta_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpage',
            name='meta_title',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
