# Generated by Django 5.0 on 2025-05-20 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0062_city_meta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='city',
            name='meta_tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
