# Generated by Django 5.0 on 2025-05-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0063_remove_city_meta_title_city_meta_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='meta_title',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='meta_tags',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
