# Generated by Django 5.0 on 2025-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0064_remove_projectpage_meta_title_projectpage_meta_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='regenerated_images/')),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
