# Generated by Django 5.0 on 2025-05-23 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_regeneratedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='regeneratedimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regenerated_images', to='project.project'),
        ),
    ]
