# Generated by Django 5.0 on 2025-05-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_regeneratedimage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_phone_number',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
