# Generated by Django 5.0 on 2025-05-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_project_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
