# Generated by Django 5.0 on 2025-05-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_projectpage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='netlify_site_url_history',
            field=models.TextField(blank=True, default=''),
        ),
    ]
