from django.urls import path
from django_grapesjs.views import GetTemplate
from .views.api import (
    ServicePageHTMLAPIView,
    CreatePageViewV2,
    GetAllTemplateView,
    RegenerateSectionView,
    SavePageView,
    CreateProjectView,
    UploadFileView,
    ProjectDomainUpdateView,
    PublishProjectView,
    CreateProjectPageView,
    ProjectDeleteAPIView,
    PageDeleteAPIView,
    CityDeleteAPIView,
    DeleteNetlifySiteView,
    save_page,
    get_version_html,
    regenerate_html,
    update_header_links,
)
from .views.web import (
    homepage,
    projects_listing,
    project_detail,
    states_listing,
    counties_listing,
    cities_listing,
    zipcodes_listing,
    city_page,
    other_page,
    grapesjs_editor,
    service_detail_page,
)

urlpatterns = [
    path('page/create/', CreatePageViewV2.as_view(), name='create_page_view'),
    path('regenerate_section/', RegenerateSectionView.as_view(), name='regenerate_section_view'),
    path('<int:project_id>/save_page/', SavePageView.as_view(), name='save_page_view'),
    path('templates/', GetAllTemplateView.as_view(), name='get_all_templates'),
    path('<int:project_id>/delete/', ProjectDeleteAPIView.as_view(), name='delete'),
    path('<int:project_id>/states/', states_listing, name='states'),
    path('<int:project_id>/counties/<int:state_id>/', counties_listing, name='counties'),
    path('<int:project_id>/cities/<int:county_id>/', cities_listing, name='cities'),
    path('<int:project_id>/zipcodes/<int:city_id>/', zipcodes_listing, name='zipcodes'),
    path('<int:project_id>/', homepage, name='homepage'),
    path('<int:project_id>/homepage/', homepage, name='homepage'),
    path('<int:project_id>/homepage/edit/', grapesjs_editor, name='homepage_edit'),
    path('<int:project_id>/page/<str:slug>/', other_page, name='other_page'),
    path('<int:project_id>/page/<str:slug>/edit/', grapesjs_editor, name='other_page_edit'),
    path('<int:project_id>/page/<int:page_id>/delete/', PageDeleteAPIView.as_view(), name='other_page_delete'),
    path('<int:project_id>/service/<str:slug>/', service_detail_page, name='service_detail_page'),
    path('<int:project_id>/service/<str:slug>/edit/', grapesjs_editor, name='service_detail_page_edit'),
    path('<int:project_id>/save/<int:page_id>/', save_page, name='page_save'),
    path('<int:project_id>/city/<int:city_id>/', city_page, name='city_page'),
    path('<int:project_id>/city/<int:city_id>/edit/', grapesjs_editor, name='city_page_edit'),
    path('<int:project_id>/city/<int:city_id>/save/', save_page, name='city_page_save'),
    path('<int:project_id>/city/<int:city_id>/delete/', CityDeleteAPIView.as_view(), name='city_page_delete'),
    path('page/<int:page_id>/', ServicePageHTMLAPIView.as_view(), name='service_page'),
    path('page/<int:page_id>/edit/', grapesjs_editor, name='page_edit'),
    path('<int:project_id>/regenerate_html/', regenerate_html, name='regenerate_html'),
    path('<int:project_id>/get_version_html/', get_version_html, name='get_version_html'),
    path('', projects_listing, name='projects'),
    path('all/', projects_listing, name='projects'),
    path('<int:project_id>/detail/', project_detail, name='project_detail'),
    path('create/', CreateProjectView.as_view(), name='create_project'),
    path('upload/', UploadFileView.as_view(), name='upload_file'),
    path('<int:project_id>/create_page/', CreateProjectPageView.as_view(), name='create_page'),
    path('<int:project_id>/update_header_links/', update_header_links, name='update_header_links'),
    path('get_template/', GetTemplate.as_view(), name='dgjs_get_template'),
    path('<int:project_id>/client_domain/', ProjectDomainUpdateView.as_view(), name='client_domain'),
    path('<int:project_id>/publish/', PublishProjectView.as_view(), name='publish_project'),
    path('<int:project_id>/delete_netlify_site/', DeleteNetlifySiteView.as_view(), name='delete_netlify_site'),
]